version: '2'

services:
  flask:
    build:
      context: app
      target: builder
    ports:
      - 8000:8000
    environment:
      - METARANK=http://metarank:8080

  qdrant:
    image: qdrant/qdrant:v1.0.3
    ports:
      - 6333:6333

  metarank:
    image: metarank/metarank:0.7.0-M1
    command: standalone --config /conf/config.yml --data /conf/events.jsonl.gz
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - .:/conf/